'use strict';

// tests for getLocation
// Generated by serverless-mocha-plugin

const mod = require('../getLocation.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('getLocation', () => {
  // set test flag
  before((done) => {
    process.env.IS_TEST = true;
    done();
  });
});
