service: website-location-service

provider:
  name: aws
  runtime: nodejs4.3

functions:
  updateLocation:
    handler: updateLocation.handler
  getLocation:
    handler: getLocation.handler

plugins:
  - serverless-build-plugin
  - serverless-mocha-plugin

custom:
  build:
    deploy: true
    modules:
      exclude:
        - aws-sdk
    method: bundle
    babel: true
    balili: true
    sourceMaps: false
    functions:
      save:
        include:
          - index.js
