service: website-location-service

provider:
  name: aws
  runtime: nodejs4.3

functions:
  save:
    handler: index.handler

plugins:
  - serverless-build-plugin
  - serverless-mocha-plugin

custom:
  build:
    deploy: false
    modules:
      exclude:
        - aws-sdk
    method: bundle
    babel: true
    balili: true
    sourceMaps: false
    functions:
