service: website-location-service

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128
  stage: dev
  region: us-east-1
  cfLogs: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  environment:
    DOMAIN: ${self:custom.domain}
    LOCATION_TABLE: ${self:custom.table.locations}
    NODE_ENV: ${self:custom.env.${self:custom.stage}}
    UPDATE_USER: ${env:YO_UPDATE_USER}

functions:
  getLocation:
    name: ${self:service}-${self:custom.stage}-get-handler
    handler: getLocation.handler
    events:
      - http: GET get
  updateLocation:
    name: ${self:service}-${self:custom.stage}-update-handler
    handler: updateLocation.handler
    events:
      - http: GET update

resources:
  Resources:
    locationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.locations}
        KeySchema:
          - AttributeName: ver
            KeyType: HASH
          - AttributeName: createdDate
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: ver
            AttributeType: N
          - AttributeName: createdDate
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-build-plugin
  - serverless-dynamodb-local
  - serverless-mocha-plugin
  - serverless-offline

custom:
  # variables
  domain: thekelvinliu.com
  env:
    dev: development
    prod: production
  stage: ${opt:stage, self:provider.stage}
  table:
    locations: ${self:service}-${self:custom.stage}-locations
  # serverless-dynamodb-local
  dynamodb:
    start:
      migration: true
  # serverless-build-plugin
  build:
    deploy: true
    modules:
      exclude:
        - aws-sdk
    method: bundle
    babel: true
    babili: true
    sourceMaps: false
    include:
      - lib.js
    functions:
      getLocation:
        include:
          - getLocation.js
      updateLocation:
        include:
          - updateLocation.js
