service: website-location-service

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true

functions:
  # getLocation:
  #   handler: getLocation.handler
  updateLocation:
    handler: updateLocation.handler
    environment:
      TEST1: this is a test
      TEST2: ${env:TEST2}
    events:
      - http: GET update

plugins:
  - serverless-build-plugin
  - serverless-mocha-plugin
  - serverless-offline

custom:
  # serverless-build-plugin
  build:
    deploy: true
    modules:
      exclude:
        - aws-sdk
    method: bundle
    babel: true
    balili: true
    sourceMaps: false
    include:
      - lib.js
    functions:
      # getLocation:
      #   include:
      #     - getLocation.js
      updateLocation:
        include:
          - updateLocation.js
