service: website-location-service

provider:
  name: aws
  runtime: nodejs4.3

functions:
  getLocation:
    handler: getLocation.handler
  updateLocation:
    handler: updateLocation.handler

plugins:
  - serverless-build-plugin
  - serverless-mocha-plugin

custom:
  build:
    deploy: true
    modules:
      exclude:
        - aws-sdk
    method: bundle
    babel: true
    balili: true
    sourceMaps: false
    include:
      - lib.js
    functions:
      getLocation:
        include:
          - getLocation.js
      updateLocation:
        include:
          - updateLocation.js
